# Generated by Django 6.0.3 on 2026-07-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninos', '0003_nino_id_guarderia'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
