# Generated by Django 6.0.3 on 2026-07-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_id_guarderia_usuario_id_guarderia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoFCM',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('plataforma', models.CharField(default='android', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_fcm', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo FCM',
                'verbose_name_plural': 'Dispositivos FCM',
                'db_table': 'dispositivo_fcm',
            },
        ),
    ]
